"""added converstion

Revision ID: 21c2a57b06d0
Revises: c91f2e8a6d31
Create Date: 2026-10-03 20:02:27.193505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c2a57b06d0'
down_revision: Union[str, Sequence[str], None] = 'c91f2e8a6d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'status')
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('messages', 'sequence_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sequence_number', sa.INTEGER(), nullable=False))
    op.drop_column('messages', 'content')
    op.add_column('conversations', sa.Column('status', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
