"""first_migration

Revision ID: 5652f059a28d
Revises: b72dc134f4ab
Create Date: 2026-10-03 15:20:31.381606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5652f059a28d'
down_revision: Union[str, Sequence[str], None] = 'b72dc134f4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the index via raw SQL to sidestep SQLite/Alembic reflection mismatch
    op.execute("DROP INDEX IF EXISTS ix_patients_user_id")
    
    # 2. Add the unique constraint via batch mode
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_patients_user_id', ['user_id'])



def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_patients_user_id', type_='unique')
        batch_op.create_index('ix_patients_user_id', ['user_id'], unique=True)

